"""
Configuration Manager Module
Handles loading, saving, and managing API configuration
"""

import os
from typing import Dict, Optional
from pathlib import Path


class ConfigManager:
    """Manages API configuration"""

    def __init__(self, config_file: str = "config.env"):
        self.config_file = config_file
        self.config = {}
        self.original_config = {}

    def load_config(self) -> Dict[str, str]:
        """Load configuration from file"""
        config = {}

        if not os.path.exists(self.config_file):
            # Return minimal defaults
            return {
                'METHOD': 'POST',
                'TIMEOUT': '30',
                'MAX_RESPONSE_TIME': '5000',
                'CORRELATION_ID': 'test'
            }

        with open(self.config_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"')
                    if value:
                        config[key] = value

        self.config = config
        self.original_config = config.copy()
        return config

    def save_config(self, config: Dict[str, str]) -> bool:
        """Save configuration to file"""
        try:
            with open(self.config_file, 'w') as f:
                f.write("# API Testing Configuration\n")
                f.write("# Generated by HTTPie-Python-Web\n\n")
                for key, value in config.items():
                    f.write(f"{key}={value}\n")
            self.config = config
            return True
        except Exception as e:
            print(f"Error saving config: {e}")
            return False

    def get(self, key: str, default: str = "") -> str:
        """Get configuration value"""
        return self.config.get(key, default)

    def set(self, key: str, value: str):
        """Set configuration value"""
        self.config[key] = value

    def update(self, updates: Dict[str, str]):
        """Update multiple configuration values"""
        self.config.update(updates)

    def backup(self):
        """Backup current configuration"""
        self.original_config = self.config.copy()

    def restore(self):
        """Restore original configuration"""
        self.config = self.original_config.copy()

    def get_all(self) -> Dict[str, str]:
        """Get all configuration values"""
        return self.config.copy()

    def mask_sensitive(self, key: str) -> str:
        """Mask sensitive configuration values"""
        value = self.config.get(key, "")
        if any(sensitive in key.upper() for sensitive in ['KEY', 'TOKEN', 'PASSWORD']):
            return "****" if value else ""
        return value
